"""TOTP secret storage — encrypted at rest, keyed per user.

Mirrors the pattern from `broker_config.py`: Fernet (AES-128-CBC + HMAC)
with a key derived from `AUTH_SECRET` via PBKDF2-HMAC-SHA256. A separate
salt keeps these keys distinct from the broker-config key — rotating
AUTH_SECRET still invalidates everything (acceptable; operators
re-enroll), but a key leak in one path doesn't compromise the other.

Two states tracked per user:
  * pending_secret_enc — generated by /enroll, not yet activated
  * active_secret_enc  — installed by /confirm; this is what 2FA verifies against

Splitting them lets the operator scan the QR, fail to confirm, and try
again without leaving a partially-enrolled row that locks them out.
"""
from __future__ import annotations

import base64
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

_SALT = b"forex-ea:totp:v1"
_KDF_ITERATIONS = 200_000

_SCHEMA = """
CREATE TABLE IF NOT EXISTS user_totp (
    username           TEXT PRIMARY KEY,
    pending_secret_enc TEXT,
    active_secret_enc  TEXT,
    enrolled_at        TEXT,
    updated_at         TEXT NOT NULL
);
"""


@dataclass(frozen=True)
class TOTPStatus:
    username: str
    enabled: bool
    pending: bool
    enrolled_at: str | None


class TOTPStore:
    def __init__(self, db_path: Path | str, secret: str) -> None:
        if not secret or len(secret) < 32:
            raise ValueError("secret must be 32+ chars (pass AUTH_SECRET)")
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._fernet = Fernet(self._derive_key(secret))
        with self._conn() as c:
            c.execute(_SCHEMA)

    @staticmethod
    def _derive_key(secret: str) -> bytes:
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=_SALT,
            iterations=_KDF_ITERATIONS,
        )
        return base64.urlsafe_b64encode(kdf.derive(secret.encode("utf-8")))

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _encrypt(self, plaintext: str) -> str:
        return self._fernet.encrypt(plaintext.encode("utf-8")).decode("ascii")

    def _decrypt(self, token: str) -> str:
        try:
            return self._fernet.decrypt(token.encode("ascii")).decode("utf-8")
        except InvalidToken as exc:
            raise ValueError("totp secret could not be decrypted (rotated AUTH_SECRET?)") from exc

    # -------------------------------------------------------------- pending

    def stage_pending(self, username: str, secret_b32: str) -> None:
        """Save a pending secret. Overwrites any prior pending value but
        leaves the active secret intact — so a confirmed user starting a
        re-enrollment still has working 2FA until they confirm the new code.
        """
        now = datetime.now(timezone.utc).isoformat()
        with self._conn() as c:
            c.execute(
                """
                INSERT INTO user_totp (username, pending_secret_enc, updated_at)
                VALUES (?, ?, ?)
                ON CONFLICT(username) DO UPDATE SET
                    pending_secret_enc = excluded.pending_secret_enc,
                    updated_at = excluded.updated_at
                """,
                (username, self._encrypt(secret_b32), now),
            )

    def get_pending_secret(self, username: str) -> str | None:
        with self._conn() as c:
            row = c.execute(
                "SELECT pending_secret_enc FROM user_totp WHERE username = ?",
                (username,),
            ).fetchone()
        if row is None or row["pending_secret_enc"] is None:
            return None
        return self._decrypt(row["pending_secret_enc"])

    def activate(self, username: str, secret_b32: str) -> None:
        """Move a confirmed secret into the active slot and clear pending."""
        now = datetime.now(timezone.utc).isoformat()
        with self._conn() as c:
            c.execute(
                """
                INSERT INTO user_totp
                    (username, active_secret_enc, pending_secret_enc, enrolled_at, updated_at)
                VALUES (?, ?, NULL, ?, ?)
                ON CONFLICT(username) DO UPDATE SET
                    active_secret_enc = excluded.active_secret_enc,
                    pending_secret_enc = NULL,
                    enrolled_at = COALESCE(user_totp.enrolled_at, excluded.enrolled_at),
                    updated_at = excluded.updated_at
                """,
                (username, self._encrypt(secret_b32), now, now),
            )

    # -------------------------------------------------------------- active

    def get_active_secret(self, username: str) -> str | None:
        with self._conn() as c:
            row = c.execute(
                "SELECT active_secret_enc FROM user_totp WHERE username = ?",
                (username,),
            ).fetchone()
        if row is None or row["active_secret_enc"] is None:
            return None
        return self._decrypt(row["active_secret_enc"])

    def is_enabled(self, username: str) -> bool:
        return self.get_active_secret(username) is not None

    def disable(self, username: str) -> bool:
        with self._conn() as c:
            cur = c.execute("DELETE FROM user_totp WHERE username = ?", (username,))
            return cur.rowcount > 0

    def status(self, username: str) -> TOTPStatus:
        with self._conn() as c:
            row = c.execute(
                "SELECT pending_secret_enc, active_secret_enc, enrolled_at FROM user_totp WHERE username = ?",
                (username,),
            ).fetchone()
        if row is None:
            return TOTPStatus(username=username, enabled=False, pending=False, enrolled_at=None)
        return TOTPStatus(
            username=username,
            enabled=row["active_secret_enc"] is not None,
            pending=row["pending_secret_enc"] is not None,
            enrolled_at=row["enrolled_at"],
        )
